version: "3.9"
services:
  django:
    container_name: vulneravel
    image: qajuda/vulneravel
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
