# Generated by Django 5.1 on 2024-08-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuario_nome_informacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacoes',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
